#obj-$(CONFIG_ARCH_DUMMY) += htc_8974-panel.o

obj-$(CONFIG_MACH_MEC_UL) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_DWG) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_TL) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_WHL) += htc_mec-panel.o
obj-$(CONFIG_MACH_A5_DWG) += htc_a5-panel.o
obj-$(CONFIG_MACH_A5_DWGL) += htc_a5-panel.o
